gestion_match_homepage:
    path:     /
    defaults: { _controller: GestionMatchBundle:Default:index }

ajout_match:
    path:     /ajmat
    defaults: { _controller: GestionMatchBundle:GestionMatches:GoToAjoutMatche }

affiche_match:
    path:     /affmatch
    defaults: { _controller: GestionMatchBundle:GestionMatches:GoToAfficheMatche }
affiche_match2:
    path:     /affmatch2
    defaults: { _controller: GestionMatchBundle:GestionMatches:GoToAfficheMatche2 }

modifier_match:
      path:     /modifmatch
      defaults: { _controller: GestionMatchBundle:GestionMatches:GoToModifMatche }
supprimer_match:
      path:     /suppmatch
      defaults: { _controller: GestionMatchBundle:GestionMatches:GoToSuppMatche }


affiche_groupe:
    path:     /affgrp
    defaults: { _controller: GestionMatchBundle:GestionGroupe:GoToAfficheGroupes }

affiche_groupe_front:
    path:     /affgrpf
    defaults: { _controller: GestionMatchBundle:GestionGroupe:GoToAfficheGroupesFront }

modifier_equipedugroupe:
    path:     /modifgrp
    defaults: { _controller: GestionMatchBundle:GestionGroupe:GoToModifGroupe }

ajout_Prono:
    path:     /ajtprono
    defaults: { _controller: GestionMatchBundle:Gestionpronos:GoToAjoutProno }
affiche_prono:
    path:     /affprono
    defaults: { _controller: GestionMatchBundle:Gestionpronos:GoToAfficheProno }
modifier_Prono:
    path:     /modifprono
    defaults: { _controller: GestionMatchBundle:Gestionpronos:GoToModifierProno }

Cart_Prono:
    path:     /cart
    defaults: { _controller: GestionMatchBundle:Gestionpronos:GoToCart }


affiche_prono_client:
    path:     /pronooo
    defaults: { _controller: GestionMatchBundle:Gestionpronos:GoToAffichePronoClient }

Affichermespronostiques:
    path:     /mespronostiques
    defaults: { _controller: GestionMatchBundle:Gestionpronos:Affichermespronostiques }

PronostiquesValide:
    path:     /valide
    defaults: { _controller: GestionMatchBundle:Gestionpronos:PronostiquesValide }
PronostiquesNonValide:
    path:     /nonvalide
    defaults: { _controller: GestionMatchBundle:Gestionpronos:PronostiquesNonValide }

parier:
    path:     /parier
    defaults: { _controller: GestionMatchBundle:Gestionpronos:Ajouterpronoclient }


calendrier:
    path:     /calendar
    defaults: { _controller: GestionMatchBundle:GestionMatches:Calendrier }






events_admin:
    path:    /events_admin
    defaults: { _controller: GestionMatchBundle:event:eventadmin }

ActivateEvent:
    path:    /ActivateEvent/{id}
    defaults: { _controller: GestionMatchBundle:event:ActivateEvent }

DeleteEvent:
    path:    /DeleteEvent/{id}
    defaults: { _controller: GestionMatchBundle:event:DeleteEv }

BlockEvent:
    path:    /BlockEvent/{id}
    defaults: { _controller: GestionMatchBundle:event:BlockEvent }

event:
    path:     /event
    defaults: { _controller: GestionMatchBundle:event:event }

update_event:
    path:     /update-event/{id}
    defaults: { _controller: GestionMatchBundle:event:updateEvent }

delete_event:
    path:     /delete-event/{id}
    defaults: { _controller: GestionMatchBundle:event:deleteEvent }

showevents:
    path:     /showevents
    defaults: { _controller: GestionMatchBundle:ticket:showevents }

take_event:
    path:     /take_event/{id}
    defaults: { _controller: GestionMatchBundle:ticket:takeevent }

new_event:
    path:     /new-event
    defaults: { _controller: GestionMatchBundle:event:newEvent }

render_event:
    path:     /render-event
    defaults: { _controller: GestionMatchBundle:event:RenderEvent }

Ticketshow:
    path:    /Ticketshow
    defaults: { _controller: GestionMatchBundle:ticket:Ticketshow }
